# -*- coding: utf-8 -*-
"""Snapcommerce Assessment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwTzyv4uSOErWUsa9HL1yYhGibzoos_I

Snapcommerce CoderByte Assessment
"""

data = 'Airline Code;DelayTimes;FlightCodes;To_From\nAir Canada (!);[21, 40];20015.0;WAterLoo_NEWYork\n<Air France> (12);[];;Montreal_TORONTO\n(Porter Airways. );[60, 22, 87];20035.0;CALgary_Ottawa\n12. Air France;[78, 66];;Ottawa_VANcouvER\n""".\\.Lufthansa.\\.""";[12, 33];20055.0;london_MONTreal\n'

# split into rows
lines = data.split("\n")
lines.pop()   # remove the last element of the list as it was a new line
lines

# split into columns
cols = []
for i in range(len(lines)):
  temp = []
  temp = lines[i].split(";")
  cols.append(temp)

for i in range(len(cols)):
  print(cols[i])

# fix the order of the columns
print(len(cols))
print(cols[0][0])

# split to and from
table = []

for i in range(len(cols)):
  temp = cols[i][0]
  cols[i][0] = cols[i][2]
  cols[i][2] = temp
  cols[i][1] = cols[i][3]
  cols[i].pop()
  row = []
  row.append(cols[i][0])
  to_from = cols[i][1].split("_")
  row.append(to_from[0])
  row.append(to_from[1])
  row.append(cols[i][2])
  table.append(row)

table

# fix individual values
for i in range(1, len(table)):
  # fix FlightCodes
  if (table[i][0]):
    table[i][0] = int (float(table[i][0]))
  else:
    table[i][0] = table[i - 1][0] + 10
  
  # Fix To Values
  x = len(table[i][1])
  temp = table[i][1]
  st = ""
  for j in range(x):
    if ord(temp[j]) == 32 or (ord(temp[j]) <= 122 and ord(temp[j]) >= 97) or (ord(temp[j]) <= 90 and ord(temp[j]) >= 65):
      st +=temp[j]
    else:
      continue
  table[i][1] = st.upper()

  # Fix From Values
  x = len(table[i][2])
  temp = table[i][2]
  st = ""
  for j in range(x):
    if ord(temp[j]) == 32 or (ord(temp[j]) <= 122 and ord(temp[j]) >= 97) or (ord(temp[j]) <= 90 and ord(temp[j]) >= 65):
      st +=temp[j]
    else:
      continue
  table[i][2] = st.upper()

  # Fix Airline Code Values 
  x = len(table[i][3])
  temp = table[i][3]
  st = ""
  for j in range(x):
    # print(temp[j], "\t", ord(temp[j]))
    if ord(temp[j]) == 32 or (ord(temp[j]) <= 122 and ord(temp[j]) >= 97) or (ord(temp[j]) <= 90 and ord(temp[j]) >= 65):
      st +=temp[j] 
  table[i][3] = st

table

for i in range(1, len(table)):
  # Fix Airline Code Values 
  x = len(table[i][3])
  temp = table[i][3]
  st = ""
  for j in range(x):
    if (ord(temp[j]) <= 122 and ord(temp[j]) >= 97) or (ord(temp[j]) <= 90 and ord(temp[j]) >= 65):
      st +=temp[j]
    if ord(temp[j]) == 32:
      if j != 0 and j != x - 1:
        st += temp[j] 
  table[i][3] = st

table

# create a table
import pandas as pd
df = pd.DataFrame (table, columns = table[0])
print (df.iloc[1:, :])